---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
  labels:
    backstage.io/kubernetes-id: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 1m0s
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: podinfo
              labels:
                backstage.io/kubernetes-id: podinfo
            spec:
              selector:
                matchLabels:
                  backstage.io/kubernetes-id: podinfo
              template:
                metadata:
                  labels:
                    backstage.io/kubernetes-id: podinfo

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: default
  labels:
    backstage.io/kubernetes-id: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      version: 6.1.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 1m0s
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: podinfo-dev
              labels:
                backstage.io/kubernetes-id: podinfo
            spec:
              selector:
                matchLabels:
                  backstage.io/kubernetes-id: podinfo
              template:
                metadata:
                  labels:
                    backstage.io/kubernetes-id: podinfo
