---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
  labels:
    backstage.io/kubernetes-id: podinfo
spec:
  interval: 30m0s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
